package com.example.CepDemo1.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor // Lombok annotation to generate a no-argument constructor
@Entity
public class StatsPost {

    @Id
    private int statsId;

    private int devicesDonated;
    private int beneficiaries;
    private int eWasteReduced;

    public StatsPost(int statsId, int devicesDonated, int beneficiaries, int eWasteReduced) {
        this.statsId = statsId;
        this.devicesDonated = devicesDonated;
        this.beneficiaries = beneficiaries;
        this.eWasteReduced = eWasteReduced;
    }

    // Getters and setters are automatically generated by Lombok's @Data annotation
}